// Generated by https://quicktype.io

export interface TokenResponse {
    Token:   string;
    Timeout: number;
    User:    User;
}

export interface User {
    UserId:          number;
    SelectedStoreId: null;
    CompanyId:       number;
    LogonName:       string;
    Fullname:        string;
    Email:           string;
    RoleId:          number;
    RoleName:        string;
    StoreIds:        any[];
    Groups:          Group[];
}

export interface Group {
    Id:   number;
    Name: string;
}
